CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS document (
	id SERIAL NOT NULL, 
	hash VARCHAR NOT NULL, 
	embedding VECTOR(1536), 
	text VARCHAR NOT NULL, 
	date_uploaded TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
)